version: '3'
services:
  wordpress:
    container_name: <project_name>_wordpress
    image: wordpress:5.3.1-apache
    restart: always
    ports:
      - 8088:80
    volumes:
      - ./:/var/www/html/
      - ./logs:/var/log/apache2/
    environment:
      WORDPRESS_DB_PASSWORD: p@s5w0rd
    networks:
      - back
  mysql: 
    container_name: <project_name>_mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: p@s5w0rd
    networks:
      - back
  phpmyadmin:
    container_name: <project_name>_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: p@s5w0rd
    networks:
      - back
networks:
  back:
    driver: "bridge"
